version: '2'

services:
  db:
    build: ./db
    image: user-service-db
    restart: always
    ports:
      - 5432:5432
    env_file: '.env'

  user-service:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service-backend:latest
    ports:
      - 9080:9080
    env_file: '.env'

  adminer:
    image: dockette/adminer
    ports:
      - 6969:80
